#define COMPONENT music

// This is being used for the Addon's Name and can be "My Addon Template Framework"
#define COMPONENT_BEAUTIFIED Music


#include "\z\aet_mp\addons\main\script_mod.hpp"
#include "\z\aet_mp\addons\main\script_macros.hpp"

#define ARR_1_NOPADDING(ARG1) ARG1
#define ARR_2_NOPADDING(ARG1,ARG2) ARG1,ARG2
#define ARR_3_NOPADDING(ARG1,ARG2,ARG3) ARG1,ARG2,ARG3
#define ARR_4_NOPADDING(ARG1,ARG2,ARG3,ARG4) ARG1,ARG2,ARG3,ARG4
#define ARR_5_NOPADDING(ARG1,ARG2,ARG3,ARG4,ARG5) ARG1,ARG2,ARG3,ARG4,ARG5
#define ARR_6_NOPADDING(ARG1,ARG2,ARG3,ARG4,ARG5,ARG6) ARG1,ARG2,ARG3,ARG4,ARG5,ARG6
#define ARR_7_NOPADDING(ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7) ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7
#define ARR_8_NOPADDING(ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8) ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8
